// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Name     string  `json:"name"`
	Location *string `json:"location,omitempty"`
	Age      int     `json:"age"`
}

type UpdateUser struct {
	Name     string  `json:"name"`
	Location *string `json:"location,omitempty"`
	Age      int     `json:"age"`
}

type User struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Location *string `json:"location,omitempty"`
	Age      int     `json:"age"`
}
